pycti/opencti_stix2.py
This uses the stix2 lib to read the indicator pattern, and extract the type and value, such that STIX indicators without 'x_opencti_observable_type' and 'x_opencti_observable_value' can be handled.
There are two main issues:
1. I don't think the new STIX2OPENCTI mapping contains all the observable types, so not everything can be imported using this.
2. The extraction only works if there is exactly one STIX Pattern 'Comparison Expression' in the pattern, so this won't work for more complex indicator patterns.
EDIT: this might be related to https://github.com/OpenCTI-Platform/opencti/issues/141?
=> Extract obserable type and value from (simple) indicator pattern during import of Indicator

pycti/opencti_connector_helper.py, pycti/opencti_stix2.py
[connector_helper] Hotfix queue must not be deleted except for new parameters (#15)
=> Hotfix queue must not be deleted except for new parameters (#15)

pycti/entities/opencti_attack_pattern.py, pycti/utils/opencti_stix2.py
AMITT misinformation framework  technique IDs are not rendered on the Techniques page in OpenCTI.  This PR provides required property parsing for AMITT techniques.
AMITT Technique ID should be listed.
AMITT Tactics STIX objects of type `x-amitt-tactic`.
Technique platforms `x-mitre-platforms` has changed to `x-amitt-platforms`.
=> new: [AMITT] add AMITT technique id parsing

pycti/entities/opencti_stix_observable.py
Hello
This is needed to get all observables of type "Domain" for example.
If there is a better way to do that, let me know
Regards
Thomas
=> [client] Add 'types' to StixObservable list() function

.gitignore, docs/conf.py, docs/requirements.txt, pycti/connector/opencti_connector_helper.py, setup.py
`sphinx-autodoc-typehints ` allows you to use Python 3 annotations for documenting acceptable argument types and return value types of functions. This allows you to use type hints in a very natural fashion, allowing you to migrate from this:
```py
def format_unit(value, unit):
"""
Formats the given value as a human readable string using the given units.
:param float|int value: a numeric value
:param str unit: the unit for the value (kg, m, etc.)
:rtype: str
"""
return '{} {}'.format(value, unit)
```
to this:
```py
from typing import Union
def format_unit(value: Union[float, int], unit: str) -> str:
"""
Formats the given value as a human readable string using the given units.
:param value: a numeric value
:param unit: the unit for the value (kg, m, etc.)
"""
return '{} {}'.format(value, …
```
=> [Doc] Add sphinx-autodoc-typehints to use Python 3 annotations

docs/pycti/pycti.rst, pycti/api/opencti_api_client.py, pycti/entities/opencti_threat_actor.py
This PR adds doc strings for the ThreatActor class and un-exports the `create_raw` function which seemed to only have been used internally.
=> [doc] Add doctrings for ThreatActor class

pycti/api/opencti_api_client.py
This can add linked relationship from client_python which could add by webUI but not api.
=> add linked relation in opencti_api_client

pycti/connector/opencti_connector_helper.py
One change in this commit https://github.com/OpenCTI-Platform/client-python/commit/6bc9897594cab95d75f9bc0ff49d268a7262cf8a broke the compatibility with Python3.5.
=> Revert edit to regain Python3.5 compatibility

pycti/connector/opencti_connector_helper.py
I noticed an odd bug with the History Connector earlier. I believe this PR fixes that error.
Here are the logs I have from the connector:
```
INFO:root:Listing Threat-Actors with filters null.
--
INFO:root:Connector registered with ID:<connector-history-id>
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
INFO:root:Starting listening stream events with SSL verify to: True
Traceback (most recent call last):
File "history.py", line 71, in <module>
HistoryInstance.start()
File "history.py", line 66, in start
self.helper.listen_stream(self._process_message)
File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 425, in listen_stream
if current_state["connectorLastEventId"] == last_event_id:
TypeError: string indices must be …
```
=> Ensure OpenCTIConnectorHelper.get_state always returns a valid state

examples/add_label_to_malware.py
As `tag` is now changed to `label` in OpenCTI, these changes would make this example a bit more understandable
=> Update and rename add_tag_to_malware.py to add_label_to_malware.py

pycti/connector/opencti_connector_helper.py
OpenSSL has deprecated Protocol Version Options as of OpenSSL 1.1.0. Use
the Python SSL interface for SSL_CTX_set_mini_proto_version() to require
TLSv1.2+.
* https://wiki.openssl.org/index.php/List_of_SSL_OP_Flags#Protocol_Version_Options
* https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TLSv1
=> [connector] Specify SSLContext.minimum_version

pycti/connector/opencti_connector_helper.py
Adapted the type format and the documentation according to the data type used here:
https://github.com/OpenCTI-Platform/client-python/blob/082c1fc977894e3ce31c13e36074fd8a304f6f0b/pycti/connector/opencti_connector_helper.py#L145
=> [ConnectorHelper] Fixed format type and documentation according to code

pycti/utils/opencti_stix2.py, tests/01-unit/test_stix.py
POC for the date error:
```
opencti_api_client = OpenCTIApiClient(api_url, api_token)
mynow = datetime.now().date()
opencti_api_client.stix2.format_date(mynow)
```
->
> INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
File "/home/user/test.py", line 4, in <module>
opencti_api_client.stix2.format_date(mynow)
File "/home/user/client-python/venv/lib/python3.9/site-packages/pycti/utils/opencti_stix2.py", line 65, in format_date
return date.isoformat(timespec="milliseconds").replace("+00:00", "Z")
TypeError: date.isoformat() takes no keyword arguments
I also converted some type hints to the old approach and did my best to add type hints to all other functions. I couldn't add one type hint to the init function, since the import of OpenCTIApiClient would have …
=> [OpenCTIStix2] Fix date bug in format_date

pycti/api/opencti_api_client.py, pycti/connector/opencti_connector_helper.py, requirements.txt, tests/cases/connectors.py
* Add the option to have a JSON format for the logs if the environment variable `OPENCTI_JSON_LOGGING` is set to True.  This adds a new dependency: `python_json_logger`.
* Add a timestamp, using a custom Formatter, in the logs to facilitate the reading.
Example of output: 
```
{"timestamp": "2021-09-15T09:34:43.106091Z", "level": "INFO", "name": "root", "message": "Listing Threat-Actors with filters null."}
{"timestamp": "2021-09-15T09:34:43.116402Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Starting new HTTP connection (1): opencti:8080"}
```
* #207 
This is the current workaround I use to have the logs in JSON format, but maybe you have a cleaner solution or a better alternative to propose.
=> Add JSON format and timestamp for logs

pycti/connector/opencti_connector_helper.py, requirements.txt, tests/cases/connectors.py
* Initialize prometheus metrics in the `OpenCTIConnectorHelper` class if the `CONNECTOR_EXPOSE_METRICS` environment variable is set to `true`. The port can be specified using the `CONNECTOR_METRICS_PORT` variable. Those metrics can be accessible from any connector using the `helper`.
Metrics created: 
Metric | Type | Description
-- | -- | --
bundle_send | Counter | The number of bundle that have been sent using the "send_bundle" function from pycti
record_send | Counter | The number of record (objects per bundle) send by the connector
run_count | Counter | The number of time the connector has run
error_count | Counter | The number of error that occurs in the connector
client_error_count | Counter | The number of error that occurs in the client when communicating with the remote data …
=> [client] add initialization of prometheus metrics in helper

pycti/entities/opencti_stix_cyber_observable_relationship.py
* change $relationship_type from "[String]" to "String" in list query
https://github.com/OpenCTI-Platform/client-python/issues/223
=> Fix stix_cyber_observable_relationship.list()

pycti/entities/opencti_malware.py
* Adding iteration of pages from GraphQL response to malware entity api
* getAll argument for malware.list() only returns first 500
=> Adding iteration of pages when all malware is requested with getAll

pycti/api/opencti_api_connector.py, pycti/connector/opencti_connector_helper.py
* Include `vhost` as a field returned from the graphql connector config query.
* Add RabbitMQ vhost configuration option
* In support of OpenCTI-Platform/opencti/issues/2199
- 👍
=> [client/api] Include rabbitmq vhost field in query (opencti-#2199)

pycti/entities/opencti_stix_cyber_observable.py
* Fix KeyError occurs when creating the observable of the Email-Message with the date field from an STIX Bundle Object which includes it.
* No
=> [stix_cyber_observable] Fix KeyError in parsing Email-Message Observable

pycti/utils/opencti_stix2.py
* Method signature is [`OpenCTIApiClient().log(level: str, message: str) -> None`][1].
* Invalid call is doing `log(message, level)`:
```py
self.opencti.log("No timezone found. Setting to UTC", "info")
```
* Change is fixing the order of parameters when calling the method.
[1]: https://github.com/OpenCTI-Platform/client-python/blob/27bf0965e405a256878b191c75030b9c22e9fcb7/pycti/api/opencti_api_client.py#L357
=> Fix param order in logging call

pycti/entities/opencti_note.py, pycti/entities/opencti_stix_core_object.py, pycti/entities/opencti_stix_cyber_observable.py, pycti/entities/opencti_stix_domain_object.py, pycti/entities/opencti_stix_object_or_stix_relationship.py, tests/cases/entities.py
* Add note types and likelihood fields to Note entity
* [issues 309](https://github.com/OpenCTI-Platform/client-python/issues/309)
Link to OpenCTI issue : [issues 2506](https://github.com/OpenCTI-Platform/opencti/issues/2506)
=> [client] Add note_types and likelihood property

pycti/connector/opencti_connector_helper.py
* Connectors automatically reconnect to broker on broker going down or connector missing too many heartbeats
* OpenCTI-Platform/client-python#324
=> [client] Connector automatic reconnect to broker

pycti/utils/opencti_stix2.py
By default, only filters and search keywords are taken into account during the export : selecting individual entities via the checkboxes is not taken into account by the list export functions.
Steps to create the smallest reproducible scenario:
1. Select multiple observables / indicators via the check boxes
2. Open the export panels and export to CSV or JSON
3. Returned format includes all observables or indicators, not the entities selected
When we select some entities via checkboxes, the file export should only contain those entities (=entities that are checked + respect the current filtering).
If no entities are selected: the workflow stay the same as it is
- txt exports (except for relationships and single entities)
- csv exports
- stix exports …
=> Export only selected entities (#1741)

pycti/utils/opencti_stix2_splitter.py
The (key, value) pair iterated across in the for loop in enlist_element can get out of sync with the data structure, as assignments of the form dict[key] = value, which are used inside the loop, are not guaranteed to preserve the [key] instance in-place, which could change the dictionary's .items() iteration source. To address this, put the keys in a list(), to take an independent copy of the keys that won't be altered by edits to the data structure inside of the loop. It does not appear that any attempts to delete a key occur, just set a value to None, so taking a copy to iterate off of should be safe.
In `enlist_element` change the `for key, value in item.items():` loop to `for key in list(item.keys()):` so that it iterates across a point-in-time snapshot of the keys. Inside the loop, …
=> [client] Iterate on snapshot of keys in OpenCTIStix2Splitter.enlist_element

tests/data/DATA-TEST-STIX2_v2.json
update the DATA-TEST to be able to test getting sub-organizations of an organization.
I just add the same entities (1 organization and 1 relation) as in the opencti project
=> [client] update DATA-TEST add sub organizations of ANSSI

pycti/entities/opencti_identity.py, pycti/entities/opencti_report.py, tests/cases/entities.py
Linked to PR : https://github.com/OpenCTI-Platform/opencti/pull/3719
* Add reliability (x_opencti_reliability) field to Report, Individual and System
* https://github.com/OpenCTI-Platform/opencti/issues/2362
=> [client] add reliability in Report (#opencti/2362)

pycti/entities/opencti_indicator.py, pycti/entities/opencti_stix_cyber_observable.py, tests/02-integration/entities/test_entity_crud.py, tests/cases/entities.py
* Extract "creators" field from indicator and observable objects
If desired, I can add to this PR by extracting the creators field from all objects, not just observables and indicators.
=> Extract creators field from indicators and observables

pycti/__init__.py, pycti/connector/opencti_connector_helper.py, pycti/connector/opencti_metric_handler.py, requirements.txt, setup.cfg, tests/01-unit/metric/test_opencti_metric_handler.py, tests/cases/connectors.py
* Add a class `OpenCTIMetricHandler` to handle prometheus metrics to keep track of the number of runs, bundles sent, errors, etc.
The class is accessible from the helper to be able to access some metrics in the connectors.
If the env `CONNECTOR_EXPOSE_METRICS` is not set, prometheus client is not initialized.
* N/A
=> [client] add OpenCTIMetricHandler class to handle prometheus metrics

docs/client_usage/getting_started.rst, pycti/api/opencti_api_client.py
* Adds support for the AuthBase class from the requests package. This way, you can implement custom authentication logic if necessary inside the implemented OpenCTI infrastructure. This is further explained in [the docs](https://requests.readthedocs.io/en/latest/user/authentication/#new-forms-of-authentication).
* Changed the wording of the `ssl_verify` and `cert` docstrings and the related description in `getting_started.rst`.
* N/A.
N/A.
=> Add custom auth header to the OpenCTIApiClient session

pycti/entities/opencti_stix_core_object.py
* Set the right type for $elementId param : [String]
* https://github.com/OpenCTI-Platform/client-python/issues/491
* https://github.com/OpenCTI-Platform/opencti/issues/4889
=> [client] Fix stix core objects list graphql query (#491)

pycti/api/opencti_api_client.py
* <img width="450" alt="image" src="https://github.com/sean0427/client-python/assets/16319704/d41902e9-bada-4efd-81b0-8c84657070c7">
* requests.session(auth=auth) is not working after API change https://requests.readthedocs.io/en/latest/api.html#api-changes
*
*
```python
from pycti import OpenCTIApiClient
from requests.auth import AuthBase
session = 'SESSION'
token ='any'
url = 'https://opencti-8080'
class CookieAuth(AuthBase):
def __init__(self, session):
self.session = session
def __call__(self, r):
r.headers['Cookie'] = f"opencti_session={self.session}"
return r
def get_client(_url, _token):
return OpenCTIApiClient(_url, _token, auth=CookieAuth(session=session))
```
=> fix api client auth problem

pycti/utils/opencti_logger.py, tests/01-unit/metric/test_opencti_metric_handler.py
* Move the `test_logger` call directly into the metric test.
* https://github.com/OpenCTI-Platform/client-python/issues/527#issuecomment-1900183738
- ~~[ ] I wrote test cases for the relevant uses case~~
- ~~[ ] I added/update the relevant documentation (either on github or on notion)~~
- ~~[ ] Where necessary I refactored code to improve the overall quality~~
Calling directly and outside any function the logger, trigger logging initialization on module import.
=> [client] Move the logger test call present in the logger module to the test file.

pycti/connector/opencti_connector_helper.py
sys.exit() does not exit the connector main thread it's only exiting current thread. I can see with local testing that the Ping thread (and main thread) are still running but the thread that process data is ended and never process data again . This lead to connectors that are not stopped or in error but are not processing data either.
* Do not exit on Exception on the ListenQueue, instead wait 10s and retry
* Removing raw stacktrace in killProgramHook, and add error with logger instead
* removing catch of KeyboardInterrupt in thread, this event is only listened by the main process
* Consistency on info logs
* Add some debug logs
* [5448](https://github.com/OpenCTI-Platform/client-python/issues/529)
If this is a relatively large or complex change, kick off the discussion by explaining why …
=> [client] Trying to have enrichment connector resilient to small network issues with rabbitMq (#5448)

pycti/api/opencti_api_client.py
Adds an option to client constructor that enables/disables health check operation.
Health check is not always desirable, for example:
* Instantiating the client in module level will slow down application start time, which is not desirable during development.
* In local environment, the upstream OpenCTI service might not be available.
Currently this can be worked around by inheriting the client class. I thought it would be nice addition.
=> Add ability to disable health check

pycti/api/opencti_api_client.py
Use `urljoin` to join create API URL. If the argument has trailing slashes, this will create a proper URL.
=> Use `urljoin` to create API URL

pycti/entities/opencti_attack_pattern.py
* When inferring the `x_mitre_id` for an Attack Pattern being imported from a STIX bundle, consider the `external_id` from any External Reference with a Source that begins with "mitre-", not only the Sources specifically listed in the OpenCTI Python SDK
* This supports [mitre-atlas dataset](https://github.com/mitre-atlas/atlas-navigator-data/blob/main/dist/stix-atlas.json) imports, which currently fail to set External ID/`x_mitre_id` when imported as a STIX Bundle.
* Checking the source name's _prefix_ instead of its presence in a fixed list allows this import code to support all current and future MITRE datasets that include External References from sources that have similar names, starting with `"mitre-"`.
- https://github.com/OpenCTI-Platform/connectors/pull/1911
N/A
=> Infer x_mitre_id if importing any MITRE dataset

pycti/entities/opencti_malware.py, pycti/utils/opencti_stix2.py, tests/02-integration/entities/test_malware.py, tests/data/basicMalwareWithSample.json
Linked to openCTI PR for fixing handling of sample_refs in malware import. Tests need to run with new openCTI changes to pass
* Added samples in Malware object and applied sample_refs to imported malwares
* https://github.com/OpenCTI-Platform/opencti/pull/6337
=> [client] Added samples to malware

pycti/entities/opencti_stix_cyber_observable.py, pycti/entities/opencti_stix_domain_object.py
Fixes #587 
Fixed graphQL queries for reports, notes and observed data in stix domain object and stix cyber observable
=> [client] Fixed objectLabel retrieval in reports, notes and observed data

pycti/connector/opencti_connector_helper.py
* Use deamon for ping alive thread, without deamon it prevents the main thread to exit when a processing thread is terminated.
* https://github.com/OpenCTI-Platform/connectors/issues/1958
=> Move PingAlive thread to deamon to allow process exit when other processing thread are terminated (#1958)

requirements.txt
* Change Prometheus client version to be less specific to the version required
* https://github.com/OpenCTI-Platform/client-python/issues/597
=> [client] Fix prometheus version compatibility

pycti/utils/constants.py
Removed linked-to ref following changes to opencti
Linked to opencti [PR](https://github.com/OpenCTI-Platform/opencti/pull/6513)
=> [client] Removed linked-to ref reference

pycti/__init__.py
Bug fix for issue https://github.com/OpenCTI-Platform/client-python/issues/586
The intrusion_set.list(getAll=True) method retrieves up to 500 records only even if the dataset contains more than 500 records.
* Add code to the list() method to retrieve additional rows of Intrusion-Set objects beyond the first 500 rows if when getAll is True.
*
*
*
=> Bug fix for issue OpenCTI-Platform#586

pycti/entities/opencti_case_incident.py
Changing 
```
if get_all:
final_data = []
data = self.opencti.process_multiple(result["data"]["caseIncidents"])
final_data = final_data + data
while result["data"]["caseIncidents"]["pageInfo"]["hasNextPage"]:
after = result["date"]["caseIncidents"]["pageInfo"]["endCursor"]
```
to 
```
if get_all:
final_data = []
data = self.opencti.process_multiple(result["data"]["caseIncidents"])
final_data = final_data + data
while result["data"]["caseIncidents"]["pageInfo"]["hasNextPage"]:
after = result["data"]["caseIncidents"]["pageInfo"]["endCursor"]
```
See issue #623 for full bug report.
Other API entites have the same issue but in my testing they did not give an error. 
See: 
~/opencti-client-python/pycti/entities/opencti_case_rfi.py
~/opencti-client-python/pycti/entities/opencti_case_rft.py …
=> python-client Fixed bug pertaining to issue #623

pycti/utils/opencti_stix2.py
* Get workflow ID only if the status is not None
* https://github.com/OpenCTI-Platform/client-python/issues/636
=> [client] Fix export an entity even if the status worfklow does not exist

pycti/api/opencti_api_client.py, pycti/connector/opencti_connector_helper.py, pycti/utils/opencti_stix2.py, pycti/utils/opencti_stix2_splitter.py, requirements.txt, tests/01-unit/utils/test_opencti_stix2_splitter.py, tests/02-integration/utils/test_stix_crud.py
=> [client] Improve worker behavior to handle complex bundle (#629)

pycti/entities/opencti_report.py, pycti/utils/opencti_stix2.py
* Add the "WithFiles" args to True when export mode equals "full" for both report list and report alone export.
Tested locally: full export of a report has now the attach file in exported json, simple export of report does not have the attach file on json.
* https://github.com/OpenCTI-Platform/client-python/issues/686
=> WithFiles was not requested when full export of report (#686)

pycti/entities/opencti_stix_core_object.py
* see opencti PR https://github.com/OpenCTI-Platform/opencti/pull/7270
* https://github.com/OpenCTI-Platform/opencti/issues/6803
=> [client] add push_analysis in stix core object (opencti/6803)

pycti/entities/opencti_attack_pattern.py, pycti/entities/opencti_campaign.py, pycti/entities/opencti_case_rfi.py, pycti/entities/opencti_case_rft.py, pycti/entities/opencti_course_of_action.py, pycti/entities/opencti_data_component.py, pycti/entities/opencti_data_source.py, pycti/entities/opencti_feedback.py, pycti/entities/opencti_grouping.py, pycti/entities/opencti_identity.py, pycti/entities/opencti_infrastructure.py, pycti/entities/opencti_location.py, pycti/entities/opencti_malware.py, pycti/entities/opencti_narrative.py, pycti/entities/opencti_note.py, pycti/entities/opencti_observed_data.py, pycti/entities/opencti_stix_core_relationship.py, pycti/entities/opencti_stix_sighting_relationship.py, pycti/entities/opencti_task.py, pycti/entities/opencti_threat_actor_group.py, pycti/entities/opencti_threat_actor_individual.py, pycti/entities/opencti_tool.py, pycti/entities/opencti_vulnerability.py, pycti/utils/opencti_stix2.py
add status x_opencti_workflow_id for entities and relationships:
*  `relationship` `grouping` `note` `case RFT` `case RFI`  `feedback` `observedData`  `campaign`  `tool` `vulnerability`
* `attackPattern` `narrative` `course of action` `dataComponent` `dataSource` `Region` `Area` `Country` `City` `Position` `Malware` `Infrastructure`  `sighting`   `Indicator` 
was already ok for:
* `Report`  `Malware Analysis`  `IR` `Incident`  `Channel` `Indicator`
* https://github.com/OpenCTI-Platform/opencti/issues/7114
*  opencti PR: https://github.com/OpenCTI-Platform/opencti/pull/7408
=> [client] add status x_opencti_workflow_id in entities & relationship (#opencti/7114)

pycti/connector/opencti_connector_helper.py
* take in account env variable SSL_VERIFY when instantiate OpenCTIApiClient
* #598 
I don't know how to test locally and the impact it has to make such a modification. Please do not merge for now.
=> Take in account env variable SSL_VERIFY when instantiate OpenCTIApiClient (#598)

pycti/utils/opencti_stix2.py
* Add one seconde to the valid_until date if valid_from equals valid_until
* https://github.com/OpenCTI-Platform/opencti/pull/7227
* https://github.com/OpenCTI-Platform/connectors/issues/2182
* https://github.com/OpenCTI-Platform/client-python/issues/692 [client]
=> [client] Ensure the valid_until date on Indicators is set to a greater value than valid_from when empty

pycti/entities/opencti_report.py
- add 2 properties into a report : participant & assignee
- [#6947](https://github.com/OpenCTI-Platform/opencti/issues/6947)
multi repository : Opencti https://github.com/OpenCTI-Platform/opencti/pull/7824
=> [client-python] get all report's properties when using csv mapper (#6947)

pycti/entities/opencti_case_rfi.py, pycti/entities/opencti_case_rft.py
make input mandatory in two queries where the '!' was missing
https://github.com/OpenCTI-Platform/client-python/issues/725
=> [client-python] missing mandatory input in Case Rfi/Rft queries (#725)

pycti/utils/opencti_stix2.py
* to prevent pagination issue, we prevent paginition ordering by _score during export
* opencti #8421
=> [client] prevent export list from ordering by _score

pycti/entities/indicator/opencti_indicator_properties.py
* observables values added on indicator properties for export
* https://github.com/OpenCTI-Platform/opencti/issues/8312
* https://github.com/OpenCTI-Platform/opencti/pull/8679
=> [client] Add observable values in indicator properties (opencti/8312)

renovate.json
* Allow renovate to create PR only outside French working hours.
*
*
=> Limit renovate PRs to nights and weekend

pycti/api/opencti_api_work.py, pycti/connector/opencti_connector_helper.py
* add draft context to current work when sending bundle to ingestion in a draft
*
*
=> [client] add draft context to work when sending bundle in draft (opencti #6577)

pycti/utils/opencti_stix2.py
Linked PR: https://github.com/OpenCTI-Platform/opencti/pull/9504
* imported bundle can now contain a `opencti_operation` with a `'patch'` value. When that is the case, the patch contained in the `opencti_field_patch` of the bundle is used to execute a field patch on the imported entity instead of an upsert
* opencti #6728
=> [client] handle new patch operation in bundle import (opencti #6728)

pycti/entities/opencti_indicator.py
* The page size listing all indicators with the "getAll" param was hardcoded to 100. To increase performance, this restriction is proposed to be removed.
* https://github.com/OpenCTI-Platform/client-python/issues/457
=> Remove harcoded first value when getting all indicators

pycti/utils/opencti_stix2.py
* remove default confidence value of 15 for sightings and let the user confidence be applied instead
* opencti #6835
=> [client] remove default confidence value of 15 for sightings (opencti #6835)

pycti/api/opencti_api_client.py
* Hide token by default and return request headers copy
* https://github.com/OpenCTI-Platform/opencti/issues/9693
to test locally, you need first to set `json_logging: true` in your config.yml, then you'll need to simulate a ping error on opencti. If you don't know how, you can try to change `getApplicationInfo` like this so that it will send a periodic error : 
```
let index = 0;
export const getApplicationInfo = () => {
index += 1;
if (index === 10) {
index = 0;
throw FunctionalError('for debug');
}
return {
version: PLATFORM_VERSION,
debugStats: {}, // Lazy loaded
};
};
```
=> [client] Hide Authorization header (opencti/9693)

pycti/api/opencti_api_client.py, pycti/connector/opencti_connector_helper.py
[client] Add markings support for workbench
See [9882](https://github.com/OpenCTI-Platform/client-python/tree/opencti/issue/9882)
=> [client] Add markings support for workbench

pycti/utils/opencti_logger.py
* replace `datetime.utcnow()` with `datetime.now(tz=timezone.utc)`
* [#3334](https://github.com/OpenCTI-Platform/connectors/issues/3334)
Quick fix to avoid errors during logging on a `sys.exit()` signal. A global rework of the AppLogger will be done soon.
=> [connector] Replace deprecated datetime.utcnow() in logger's formatter

requirements.txt, setup.cfg
* Loose opentelemetry-api/sdk required versions in dependencies
* https://github.com/OpenCTI-Platform/client-python/issues/818
Opentelemetry python packages available versions are.
```bash
$ python -m pip index versions opentelemetry-sdk
Available versions: 1.30.0, 1.29.0, 1.28.2, 1.28.1, 1.28.0, 1.27.0, 1.26.0, 1.25.0, 1.24.0, 1.23.0, 1.22.0, 1.21.0, 1.20.0, 1.19.0, 1.18.0, 1.17.0, 1.16.0, 1.15.0, 1.14.0, 1.13.0, 1.12.0, 1.11.1, 1.11.0, 1.10.0, 1.9.1, 1.9.0, 1.8.0, 1.7.1, 1.7.0, 1.6.2, 1.6.1, 1.6.0, 1.5.0, 1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 1.0.0
```
We are currently using 1.22.0, released in December 2023 ! https://github.com/open-telemetry/opentelemetry-python/commit/e6602ffc7434929fa377beae2f0d14f6d6993997
Using the `tox `tool, and based on successful package installation with `pip …
=> [deps]: loose opentelemetry-xxx required versions (#818)

pycti/connector/opencti_connector_helper.py, pycti/utils/opencti_stix2.py
* only add draft_id to work when draft is created by connector
*
* opencti #9300
=> [client] only add draft_id to work when draft is created by connector (opencti #9300)

requirements.txt, setup.cfg
* Loose `requests `required versions in dependencies
* https://github.com/OpenCTI-Platform/client-python/issues/857
From [Changelog ](https://requests.readthedocs.io/en/latest/community/updates/#release-history)(consulted on March 6, 2025) last Security issue was patch in 2.32..0. So we tested from this version to latest one with python versions 3.8 -> 3.12.
Using the tox tool, and based on successful package installation with `pip`, vulnerability check with `pip-audit` and tests performed with `pytest`, we can conclude that we are, at a minimum, compatible with requests versions [2.32.0 to 2.32.3] when using Python [3.8 to 3.12].
Investigation Notion Page : https://www.notion.so/filigran/Loose-Requests-required-versions-in-opencti-python-client-1ae8fce17f2a809c9eebfec93400b1c4?pvs=4
=> [deps]: loose requests required versions

pycti/api/opencti_api_client.py, pycti/api/opencti_api_connector.py, pycti/connector/opencti_connector.py, pycti/connector/opencti_connector_helper.py, requirements.txt
See #850
Related to https://github.com/OpenCTI-Platform/opencti/issues/10046
=> [client] Introduce api protocol helper for listening connectors (#850)

pycti/connector/opencti_connector_helper.py
* OpenCTIConnector last argument is listen_callback_uri with default value None, which needs to be set when using protocol API instead of default AMQP. However, previous code in the connector helper always sets the argument to an URL based on two other config variables with default values, resulting in all connectors registering with a listen_callback_uri. The protocol is not kept in OpenCTI and the workers check listen_callback_uri to determine if they need to connect to the URI. All connectors are then trying to reach the default URI when using AMQP protocol.
This change fixes it by setting the listen_callback_uri argument only if API protocol.
=> [client] do not register API listening URI when using AMQP protocol

pycti/connector/opencti_connector_helper.py
* add_expectations was being called twice when sending a bundle
*
* opencti #10523
*
=> [client] fix work expectations computation (Opencti #10523)

.github/workflows/auto-set-labels.yml
* Add automatically "filigran team" labels on PR from Filigran employees.
Same as opencti one https://github.com/OpenCTI-Platform/opencti/blob/master/.github/workflows/auto-set-labels.yml
*
*
=> [CI] add auto label filigran team

pycti/api/opencti_api_client.py, pycti/connector/opencti_connector_helper.py
See #844
After merge, please take care of https://github.com/OpenCTI-Platform/opencti/issues/9992
=> [client] Add capability to add custom headers in opencti http client (#844)

pycti/entities/opencti_identity.py
* Add score on Organization
* https://github.com/OpenCTI-Platform/opencti/issues/9811
* OpenCTI PR:
* https://github.com/OpenCTI-Platform/opencti/pull/10703
=> [client] Add score on Organization

pycti/utils/opencti_stix2.py
* use internal_id for patch operation instead of standard_id, to handle patches that cause a standard_id change
related opencti PR: https://github.com/OpenCTI-Platform/opencti/pull/10825
* opencti #10817
*
=> [client] now use internal id when possible for patch operations

scripts/clone-opencti.sh
* hardcode opencti clone to clone release/current if current branch is release/current
*
*
*
=> [client] test fix build target release/current

pycti/entities/opencti_stix_cyber_observable.py
* src_ref and dst_ref weren't handled directly in creation. This could cause unwanted deduplication to occur
*
* opencti #10869
*
=> [client] handle src_ref and dst_ref during network traffic creation (opencti #10869)

pycti/entities/opencti_identity.py, pycti/utils/constants.py
* add new constant 'SECURITY'
* add security_platform_type
[link to opencti PR ](https://github.com/OpenCTI-Platform/opencti/pull/11045)
* https://github.com/OpenCTI-Platform/opencti/issues/10452
=> [client] new Security-Platform IdentityType (#10452)

pycti/entities/opencti_stix_core_relationship.py, pycti/entities/opencti_stix_sighting_relationship.py, pycti/utils/opencti_stix2.py
* revert draft was missing for sightings & relationships
* share/unshare was missing for sightings & relationships
opencti PR https://github.com/OpenCTI-Platform/opencti/pull/11308
* opencti #906 
*
=> [client] background tasks fixes (opencti #10274)

pycti/connector/opencti_connector_helper.py, pycti/utils/opencti_stix2.py, pycti/utils/opencti_stix2_splitter.py, tests/01-unit/utils/test_opencti_stix2_splitter.py
* split_bundle_with_expectations now reports the number of discarded elements due to incompatible type
* when splitting bundle in import_bundle, we now report_expectation with an error for every discarded element
* changed all calls to split_bundle_with_expectations  to handle new signature
result of new report expectation with error:
octi PR: https://github.com/OpenCTI-Platform/opencti/pull/11365
* opencti #11359
*
=> [client] report discarded objects during splitting as processed in work (opencti #11359)

pycti/api/opencti_api_client.py, pycti/api/opencti_api_internal_file.py, pycti/api/opencti_api_playbook.py, pycti/utils/opencti_stix2.py
Add client python api to delete internal files
https://github.com/OpenCTI-Platform/opencti/issues/11463
=> [client] Can't bulk delete workbenches or files (#11463)

pycti/entities/opencti_stix_core_object.py
* add missing "s" in connectorIds
* https://github.com/OpenCTI-Platform/opencti/issues/11548
=> [client] Enriching External Reference Objects from User Interface produces GraphQL error (#11548)

pycti/utils/opencti_stix2.py
* extracted object markings were initialized to [] instead of None, causing ingestion to not apply default values
*
* https://github.com/OpenCTI-Platform/opencti/issues/12095
*
=> [client] initialize markings to None instead of [] (opencti #12095)

.drone.yml
Add OpenCTI EE license in drone CI
=> Add EE license in CI

pycti/entities/opencti_case_rfi.py, pycti/entities/opencti_case_rft.py, pycti/entities/opencti_grouping.py
* add missing content attribute at create & import for groupings, RFI & RFT
* https://github.com/OpenCTI-Platform/opencti/issues/11874
=> [client] Grouping content is erased when approving Draft (#11874)
