OpenCTI-Platform/client-python

- .gitignore
- .readthedocs.yml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/modules/api.rst
- docs/modules/connector.rst
- docs/modules/entities.rst
- docs/modules/modules.rst
- docs/modules/utils.rst
- docs/requirements.txt
- pycti/api/__init__.py
- pycti/connector/__init__.py
- pycti/entities/__init__.py
- pycti/utils/__init__.py
With this PR we get a basic doc structure for ReadTheDocs.
> Add basic sphinx doc structure for RTD

- docs/pycti/pycti.rst
- docs/requirements.txt
- requirements.txt
This *should* fix the doc building for the latest API changes.
> Fix doc building for API changes in v4

- .gitignore
From https://github.com/github/gitignore/blob/master/Python.gitignore
> Update .gitignore with more directories

- .pre-commit-config.yaml
- setup.py
`pre-commit` is a framework for managing and maintaining multi-language pre-commit hooks.
https://pre-commit.com/#intro 
> Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks.
```console
$ pip install -e .[dev,doc]
$ pre-commit install
$ git add .pre-commit-config.yaml
$ git commit -m "pre-commit setup"
black....................................................................Passed
Check …
```
> pre-commit setup

- pycti/entities/opencti_stix_cyber_observable.py
change then variable of the observable type text for making possible to create new observables of this type
> text observable variable changed

- pycti/connector/opencti_connector_helper.py
Add `create_ssl_context()` function to require TLSv1.2, certificate
validation, and disable insecure SSL flags by default.
> [connector] Create default SSL context for pika

- pycti/connector/opencti_connector_helper.py
[connector] Standardize pika SSL control flow
> [connector] Standardize pika SSL control flow

- pycti/entities/opencti_report.py
Adding a few more fixes for #161
> Wrong missing function argument in opencti_report.py

- .isort.cfg
- .pre-commit-config.yaml
- examples/add_external_reference_to_report.py
- examples/cmd_line_tag_latest_indicators_of_threat.py
- examples/create_campaign_attributed-to_intrusion_set.py
- examples/create_indicator_of_campaign.py
- examples/create_intrusion_set.py
- examples/create_report_with_author.py
- examples/export_incident_stix2.py
- examples/export_incidents_stix2.py
- examples/export_intrusion_set_stix2.py
- examples/export_report_stix2.py
- examples/upload_file_to_intrusion_set.py
- pycti/__init__.py
- pycti/api/opencti_api_client.py
- pycti/api/opencti_api_connector.py
- pycti/connector/opencti_connector_helper.py
- pycti/entities/opencti_identity.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_threat_actor.py
- pycti/utils/opencti_stix2.py
- pycti/utils/opencti_stix2_update.py
- pycti/utils/opencti_stix2_utils.py
- setup.py
- tests/test_indicators.py
- [client] Add black-compatible isort config
- [client] Sort all imports with isort
- [client] Add isort to pre-commit hooks
> [client] Sort imports with isort; add pre-commit hooks

- pycti/connector/opencti_connector_helper.py
- pycti/entities/opencti_report.py
Added logging levels debug and warn to OpenCTIConnectorHelper
> Added logging levels DEBUG and WARN

- pycti/connector/opencti_connector_helper.py
[client] Refactor connector helper
* Add missing function type annotations.
* Simplify control flow.
* Annotate pylint violations.
* Use lazy log string evaluation.
* Replace string concatenation with f-strings.
* Refactor check_max_tlp().
> Lint connector helper

- pycti/utils/opencti_stix2.py
Corrected entity_type type hint from Dict to str
> [OpenStix2] Corrected entity_type type hint from Dict to str

- examples/add_tool_usage_to_intrusion-set.py
- examples/create_incident_with_ttps_and_indicators.py
- examples/create_indicator_of_campaign.py
- examples/delete_intrusion_set.py
- examples/delete_relation.py
- examples/export_incident_stix2.py
- examples/export_incidents_stix2.py
- examples/get_all_indicators_using_pagination.py
- examples/get_all_reports_using_pagination.py
- examples/get_observable_exact_match.py
- examples/get_observables_search.py
- examples/get_reports_about_intrusion_set.py
- examples/update_observable_attributes.py
I fixed a couple of examples which threw errors upon execution or improved others.
The only two examples which I didn't finish are the async exports.
> [examples] Example fixes

- pycti/entities/opencti_label.py
- tests/02-integration/entities/test_entity_crud.py
* Added 'standard_id' for Label read operations
* Added test case to verify all entities return a standard_id value 
* none
None
> [client] Added Stix ID to Label

- pycti/entities/opencti_stix_cyber_observable_relationship.py
Reverts OpenCTI-Platform/client-python#224
> Revert "Fix stix_cyber_observable_relationship.list()"

- pycti/utils/opencti_stix2.py
* Adding support for listing sighting relationships.
*#236
> Adding support for listing sighting relationships, fixes #236

- pycti/connector/opencti_connector_helper.py
* Handle send_bundle properly when work_id is empty (like for stream connector)
* https://github.com/OpenCTI-Platform/connectors/issues/588
> [connector_helper] Fix send_bundle if work_id is empty

- pycti/connector/opencti_connector_helper.py
- pycti/utils/opencti_stix2_splitter.py
* Improved handling of empty bundles
* https://github.com/OpenCTI-Platform/connectors/issues/588
- [] I wrote test cases for the relevant uses case
> [client] Properly handle empty bundles

- .github/workflows/codeql-analysis.yml
* See https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
*
*
> [github] Upgrade CodeQL to v2

- .circleci/config.yml
- .drone.yml
- tests/cases/entities.py
- tests/conftest.py
* Set up test suite using drone
* Configure tests to use the drone
* Builds are only executed when there's a new release
> [tests] Migrate test suite to drone

- .circleci/config.yml
- .flake8
- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
* Remove trailing whitespaces
* Add config file for flake8 (same as for the connectors)
* Update python image for circleci formatting check
> [refactor] remove trailing whitespaces and add flake8 config file

- pycti/entities/opencti_incident.py
- pycti/entities/opencti_stix_core_relationship.py
* [client] Implement incident new attributes
> [client] Implement incident new attributes

- pycti/__init__.py
> [client] Release 5.2.2

- pycti/utils/opencti_stix2.py
https://github.com/OpenCTI-Platform/opencti/issues/2804
> List exports bugs for contained data #2804

- pycti/entities/opencti_case.py
Export of cases bug fix
https://github.com/OpenCTI-Platform/opencti/issues/2821 (bug 2)
> [client-python] cases filtering & export bug fix (#2821)

- pycti/entities/opencti_case_rfi.py
- pycti/entities/opencti_case_rft.py
* Fix old reference to StixMetaRelationshipAddInput
> [client] Fix old reference to StixMetaRelationshipAddInput

- pycti/__init__.py
- pycti/api/opencti_api_client.py
- pycti/entities/opencti_case_task.py
- pycti/utils/opencti_stix2.py
- tests/cases/entities.py
https://github.com/OpenCTI-Platform/opencti/issues/2846
> [client-python] Implements Task (#opencti/2846)

- pycti/connector/opencti_connector_helper.py
https://github.com/OpenCTI-Platform/opencti/issues/2308
Add support for more options + loading cert from string or files
> [client] Improve RabbitMQ SSL context generation (#2308)

- .drone.yml
* Revert https://github.com/OpenCTI-Platform/client-python/commit/c2e380a5d75cd09cf20fe173c2a0470815dfef65 
* Add tests for python 3.11
* https://github.com/OpenCTI-Platform/connectors/pull/1189 
minimal change
> Fix python version

- pycti/utils/opencti_stix2.py
**Related to :** https://github.com/OpenCTI-Platform/connectors/pull/1388
* remove unused parameters
* Fix export of relationships (we used to put standard_id in object_to_get instead of the entity object)
* https://github.com/OpenCTI-Platform/connectors/issues/1387
> [client] fix export-file-stix list export (#connectors/1387)

- pycti/connector/opencti_connector_helper.py
Update `_send_bundle` to use the imported `LOGGER`. Also, updated from `info` to `debug`. When using `send_stix2_bundle` the message `Bundle has been sent` was multiplied significantly due to the for loop using `enumerate` on `bundles`.
> Send bundle log level

- pycti/entities/opencti_report.py
* Handle content in report creation and import
* #519 
* https://github.com/OpenCTI-Platform/opencti/issues/4857
> [client] Add content in report creation (#519)

- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_core_relationship.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_stix_nested_ref_relationship.py
- pycti/entities/opencti_stix_sighting_relationship.py
- pycti/utils/opencti_stix2.py
See https://github.com/OpenCTI-Platform/opencti/issues/5370
> [client] Adapt client for platform API changes (opencti/issues/5370)

- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_stix_object_or_stix_relationship.py
- pycti/entities/opencti_vulnerability.py
*
*
* https://github.com/OpenCTI-Platform/opencti/issues/5676
> [client] Model enforcing must be fixed to convert base_score to float.(#5676)

- pycti/api/opencti_api_client.py
This is a small fix that removes a [mutable default argument](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) with better default.
> Remove mutable default argument from `OpenCTIApiClient.query`

- .drone.yml
- examples/get_reports_about_intrusion_set.py
- pycti/entities/opencti_malware_analysis.py
related to https://github.com/OpenCTI-Platform/opencti/issues/6056 
Follow up of PR https://github.com/OpenCTI-Platform/opencti/pull/6080
> [client] update to MalwareAnalysisAddInput api

- pycti/connector/opencti_connector_helper.py
- pycti/entities/opencti_campaign.py
- pycti/entities/opencti_case_incident.py
- pycti/entities/opencti_case_rfi.py
- pycti/entities/opencti_case_rft.py
- pycti/entities/opencti_channel.py
- pycti/entities/opencti_data_component.py
- pycti/entities/opencti_event.py
- pycti/entities/opencti_grouping.py
- pycti/entities/opencti_incident.py
- pycti/entities/opencti_indicator.py
- pycti/entities/opencti_infrastructure.py
- pycti/entities/opencti_intrusion_set.py
- pycti/entities/opencti_malware.py
- pycti/entities/opencti_malware_analysis.py
- pycti/entities/opencti_note.py
- pycti/entities/opencti_observed_data.py
- pycti/entities/opencti_report.py
- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_core_relationship.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_stix_object_or_stix_relationship.py
- pycti/entities/opencti_stix_sighting_relationship.py
- pycti/entities/opencti_threat_actor.py
- pycti/entities/opencti_threat_actor_group.py
- pycti/entities/opencti_threat_actor_individual.py
- pycti/utils/opencti_stix2.py
Organization sharing behavior change for upsert and enrichment
- Add auto resolution for enrichment connector
- Support custom attributes 
- Support for files fetch option
> [client] Enrichment auto resolution and organization sharing propagation

- pycti/api/opencti_api_client.py
- pycti/entities/opencti_external_reference.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
> [client] Improve hub/children synchronization pattern (#6253)

- pycti/api/opencti_api_client.py
- pycti/api/opencti_api_work.py
- pycti/connector/opencti_connector_helper.py
> [client] Add support to write connectors bundle to files and/or to queue (#603)

- pycti/utils/opencti_stix2.py
*
*
* [issue/305](https://github.com/OpenCTI-Platform/client-python/issues/605)
* [opencti/6499](https://github.com/OpenCTI-Platform/opencti/issues/6499)
*
> [client] create get_reader method from entity_type (#605)

- pycti/entities/opencti_stix_cyber_observable.py
issue: https://github.com/OpenCTI-Platform/opencti/issues/6681
> [client] typo in pycti/entities/opencti_stix_cyber_observable.py (#6681)

- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
* Update export report pdf by passing markings
* https://github.com/OpenCTI-Platform/opencti/issues/5797
This pull request is related to the ones in the `Open-CTI` and `Connectors` :
* https://github.com/OpenCTI-Platform/opencti/pull/6030
* https://github.com/OpenCTI-Platform/connectors/pull/2011
> [client] Define file marking definitions (#opencti/5797)

- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
* Update export report pdf by passing markings
* https://github.com/OpenCTI-Platform/opencti/issues/5797
This pull request is related to the ones in the `Open-CTI` and `Connectors` :
* https://github.com/OpenCTI-Platform/opencti/pull/6030
* https://github.com/OpenCTI-Platform/connectors/pull/2011
> [client] Define file marking definitions (#opencti/issue/5797)

- examples/upload_file.py
- pycti/api/opencti_api_client.py
> [client-python] upload_file now accepts optional arg file_markings (#631)

- examples/export_incident_stix2.py
- examples/export_intrusion_set_stix2.py
- examples/export_report_stix2.py
- pycti/connector/opencti_connector_helper.py
- pycti/entities/opencti_intrusion_set.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_stix_object_or_stix_relationship.py
- pycti/utils/opencti_stix2.py
Error when importing text files or PDFs (#6942)
> Error when importing text files or PDFs (#6942)

- scripts/clone-opencti.sh
* Forgot to remove check on optionnal parameter on CI script.
*
*
> Fix parameters in CI script

- pycti/entities/opencti_stix_core_relationship.py
- pycti/entities/opencti_stix_nested_ref_relationship.py
- pycti/entities/opencti_stix_object_or_stix_relationship.py
- pycti/entities/opencti_stix_sighting_relationship.py
> [client] Report Full export (STIX/JSON) doesn't include relationships (#669)

- pycti/entities/opencti_stix_cyber_observable.py
> [client] promote to indicator return updated

- pycti/utils/opencti_stix2.py
* Delete pre control in container
* [#7332](https://github.com/OpenCTI-Platform/opencti/issues/7332)
*
> [Export] Fix exporting a container

- pycti/connector/opencti_connector.py
* see https://github.com/OpenCTI-Platform/opencti/pull/7192 for more info
*
*
> [client] add new connector type

- pycti/api/opencti_api_client.py
* Add `ssl_verify`, `cert` and `proxies` parameters when using `fetch_opencti_file` to support self-signed certificate
* https://github.com/OpenCTI-Platform/connectors/issues/2215
* https://github.com/OpenCTI-Platform/client-python/issues/682
* https://github.com/OpenCTI-Platform/opencti/issues/7349
> [client] Fix SSL certificate self-signed to be supported issue

- pycti/entities/opencti_stix_core_relationship.py
- pycti/entities/opencti_stix_sighting_relationship.py
- scripts/clone-opencti.sh
Closes https://github.com/OpenCTI-Platform/opencti/issues/7174
> [client-python] Fix search args in relationships (#opencti/7174)

- pycti/entities/opencti_vulnerability.py
* cisa kev key added on creation mutation and vulnerability query
*
* https://github.com/OpenCTI-Platform/opencti/issues/7390
*
* opencti: https://github.com/OpenCTI-Platform/opencti/pull/7646
> [client] Support of KEV field for vulnerability entity (#7390)

- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/entities/opencti_stix_object_or_stix_relationship.py
- pycti/entities/opencti_vulnerability.py
* epss score and epss percentile keys added on creation mutation and vulnerability query
* https://github.com/OpenCTI-Platform/opencti/issues/3568
*
* https://github.com/OpenCTI-Platform/opencti/pull/7802
> [client] Add EPSS Support for Vulnerability Entity (#3568)

- pycti/__init__.py
- pycti/entities/opencti_stix_core_object.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/stix_cyber_observable/opencti_stix_cyber_observable_properties.py
- pycti/utils/constants.py
* Added support for a new StixCyberObservable type: Personas (aka monikers)
*
*
> [client] added persona support

- pycti/__init__.py
* Fix - Added missing channel import to pycti
* #721 
* https://github.com/OpenCTI-Platform/connectors/issues/2579
> [client-python] Added missing channel import to pycti

- pycti/entities/opencti_stix_core_object.py
* Allow deletion of stix core objects
* No relevant open issues found for "delete" or "remove"
I pulled the delete function from another class and reworked it for Stix Core Object
> [client-python] Allow deletion of stix core objects

- pycti/utils/opencti_stix2.py
[client] Improve sighting ingestion speed removing extra resolution
> [client] Improve sighting ingestion speed removing extra resolution

- pycti/connector/opencti_connector_helper.py
* Convert str environment variables to float from docker-compose
* Fixed default values ​​to float default value
* #729
> [Client-python] Fix error with queue_threshold

- pycti/utils/opencti_stix2_splitter.py
- tests/01-unit/utils/test_opencti_stix2_splitter.py
- tests/data/bundle_with_internal_ids.json
- tests/data/mono-bundle-entity.json
Allow internal id in the split
> [client] Allow internal id in the split

- pycti/api/opencti_api_client.py
- pycti/utils/opencti_stix2.py
Linked to https://github.com/OpenCTI-Platform/opencti/pull/8659
*
*
* https://github.com/OpenCTI-Platform/opencti/issues/6577
> [client] add draft_id header handling (opencti/6577)

- pycti/api/opencti_api_client.py
- pycti/connector/opencti_connector_helper.py
* instead of creating a workbench, now create and ingest in a draft if possible (FF activated). Otherwise, still create a workbench
* add ability to handle messages asking for message to be handled in a specific draft context
Related PR : https://github.com/OpenCTI-Platform/opencti/pull/8858
* https://github.com/OpenCTI-Platform/opencti/issues/6577
> [client] add ability to ingest bundle in draft (opencti/6577) 

- pycti/entities/opencti_external_reference.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/utils/opencti_stix2.py
* Take into account marking on files at import 
* #787
> [client] Take into account marking on files at import (#787)

- .drone.yml
* upgrade rabbitMq version for local dev and drone test runs.
* relates but does not close https://github.com/OpenCTI-Platform/opencti/issues/8894
> Upgrade rabbitmq to 4 for drone and local dev(#8894)

- pycti/entities/opencti_case_incident.py
- pycti/entities/opencti_case_rfi.py
- pycti/entities/opencti_case_rft.py
- pycti/entities/opencti_task.py
* add objectAssignee attributes in case-rfi and case-rft
* https://github.com/OpenCTI-Platform/opencti/issues/7728
> [client] Add assignee through automation playbook (#7728)

- pycti/entities/opencti_case_rfi.py
- pycti/entities/opencti_case_rft.py
* Add "Severity" and "Priority" attribute for ingestion
* https://github.com/OpenCTI-Platform/opencti/issues/7648
> [client] [Playbook] Modify severity field with playbooks (#7648)

- docs/conf.py
> Update copyright to 2025

- pycti/utils/opencti_stix2.py
Linked PR: https://github.com/OpenCTI-Platform/opencti/pull/9684
*
*
*
*
> [client] fix patch operation for external references

- pycti/utils/opencti_stix2.py
* handle file update in patch operation 
* opencti #9300
> [client] handle file update in patch operation (opencti #9300)

- pycti/connector/opencti_connector_helper.py
- pycti/utils/opencti_stix2.py
> [client] handle draft read only errors (opencti #9300)

- pycti/connector/opencti_connector_helper.py
* Handle `force_validation` 
* Close https://github.com/OpenCTI-Platform/opencti/issues/9760
> [client] add `force_validation` to `send_stix2_bundle` (#9760)

- pycti/entities/opencti_indicator.py
* platform instead of plateform
* https://github.com/OpenCTI-Platform/opencti/pull/10273
> [client] Fix a spelling mistake (#8245)

- pycti/entities/indicator/opencti_indicator_properties.py
*  add hashes to indicator observable values graphql fragment
Linked to https://github.com/OpenCTI-Platform/opencti/pull/10426
* opencti #10277
> [client] add hashes to indicator observable values graphql fragment (opencti #10277)

- pycti/api/opencti_api_client.py
- pycti/entities/opencti_group.py
- pycti/entities/opencti_role.py
- pycti/entities/opencti_settings.py
- pycti/entities/opencti_user.py
> [client] Fix administrative entities parsing (#827)

- pycti/entities/opencti_attack_pattern.py
- pycti/entities/opencti_campaign.py
- pycti/entities/opencti_case_incident.py
- pycti/entities/opencti_case_rfi.py
- pycti/entities/opencti_case_rft.py
- pycti/entities/opencti_course_of_action.py
- pycti/entities/opencti_data_component.py
- pycti/entities/opencti_data_source.py
- pycti/entities/opencti_event.py
- pycti/entities/opencti_feedback.py
- pycti/entities/opencti_grouping.py
- pycti/entities/opencti_identity.py
- pycti/entities/opencti_incident.py
- pycti/entities/opencti_infrastructure.py
- pycti/entities/opencti_intrusion_set.py
- pycti/entities/opencti_language.py
- pycti/entities/opencti_location.py
- pycti/entities/opencti_malware.py
- pycti/entities/opencti_malware_analysis.py
- pycti/entities/opencti_narrative.py
- pycti/entities/opencti_note.py
- pycti/entities/opencti_observed_data.py
- pycti/entities/opencti_opinion.py
- pycti/entities/opencti_stix_core_relationship.py
- pycti/entities/opencti_stix_sighting_relationship.py
- pycti/entities/opencti_task.py
- pycti/entities/opencti_threat_actor_group.py
- pycti/entities/opencti_threat_actor_individual.py
- pycti/entities/opencti_tool.py
- pycti/entities/opencti_vulnerability.py
* status wasn't retrieved from multipe entity types
*
* opencti #8389
*
> [client] added missing status in query fragments (opencti #8389)

- pycti/entities/opencti_stix_sighting_relationship.py
* add objectOrganization to sighting addInput
* closes https://github.com/OpenCTI-Platform/opencti/issues/11483
> [client] add objectOrganization to sighting creation

- pycti/utils/opencti_stix2.py
* fix handling of external reference delete for delete operation
*
*  [opencti #11958](https://github.com/OpenCTI-Platform/opencti/issues/11958)
*
> [client] fix handling of external reference delete for delete operation (opencti #11958)

- pycti/entities/opencti_external_reference.py
- pycti/entities/opencti_stix_cyber_observable.py
- pycti/entities/opencti_stix_domain_object.py
- pycti/utils/opencti_stix2.py
* [client] Add embedded option to file upload
* Closes #968
> [client] Add embedded option to file upload (#968)

- .drone.yml
* upgrade rabbitMq version for Drone
* relates to https://github.com/OpenCTI-Platform/opencti/issues/12457
> [CI] upgrade rabbitMq version on Drone (#12457)
